const seed=[
{id:"vap149",name:"Vaporeon ex #149/131",set:"Prismatic Evolutions · 2025",grade:9,cert:"136142566",value:215,purchase:null,icon:"💧"},
{id:"eev174",name:"Eevee ex #174",set:"SVP Promo · 2025",grade:9,cert:"136142568",value:30,purchase:null,icon:"✨"},
{id:"cha074",name:"Charizard ex #074",set:"Paldean Fates Tin · 2024",grade:9,cert:"136142569",value:38,purchase:null,icon:"🔥"},
{id:"cha228",name:"Charizard ex #228/197",set:"Obsidian Flames · 2023",grade:9,cert:"136142567",value:55,purchase:null,icon:"🏆"}];
const KEY="cardvault.v2";let state=JSON.parse(localStorage.getItem(KEY)||"null")||{cards:seed,watch:[],history:[],market:[]};
const euro=n=>(+n||0).toLocaleString("es-ES",{style:"currency",currency:"EUR"});const total=()=>state.cards.reduce((a,x)=>a+(+x.value||0),0);function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function render(){document.querySelector("#cards").innerHTML=state.cards.map(x=>{let p=x.purchase!=null?(x.value-x.purchase):null;return `<article class="card"><div class="thumb">${x.photo?`<img src="${x.photo}">`:x.icon||"🃏"}</div><div><h3>${x.name}</h3><div class="meta">${x.set||""}<br>${x.cert?"Cert. "+x.cert:""}</div><span class="grade">PSA ${x.grade}</span></div><div class="price">${euro(x.value)}${p==null?"":`<div class="profit ${p>=0?"up":"down"}">${p>=0?"+":""}${euro(p)}</div>`}</div></article>`}).join("");document.querySelector("#total").textContent=euro(total());document.querySelector("#count").textContent=state.cards.length+" cartas";let prev=state.history.at(-1)?.total;document.querySelector("#change").textContent=prev==null?"Sin comparación anterior":(total()-prev>=0?"+":"")+euro(total()-prev)+" desde snapshot";document.querySelector("#watchList").innerHTML=state.watch.length?state.watch.map((x,i)=>`<div class="card"><div class="thumb">👁️</div><div><h3>${x.name}</h3><div class="meta">Objetivo ≤ ${euro(x.target)}</div></div><button onclick="removeWatch(${i})">×</button></div>`).join(""):'<div class="empty">No sigues ninguna carta todavía.</div>';renderHistory()}
function renderHistory(){const h=[...state.history].reverse();document.querySelector("#history").innerHTML=h.slice(0,10).map(x=>`<div class="historyRow"><span>${new Date(x.at).toLocaleString("es-ES")}</span><b>${euro(x.total)}</b></div>`).join("");drawChart()}
function drawChart(){const c=document.querySelector("#chart"),dpr=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*dpr;c.height=r.height*dpr;const g=c.getContext("2d");g.scale(dpr,dpr);g.clearRect(0,0,r.width,r.height);let a=state.history.slice(-30);if(a.length<2){g.fillStyle="#8992ad";g.font="13px -apple-system";g.fillText("Guarda 2 snapshots para ver la evolución",12,30);return}let vals=a.map(x=>x.total),mn=Math.min(...vals),mx=Math.max(...vals);if(mx===mn){mx++;mn--}g.strokeStyle="#eef2ff";g.lineWidth=2;g.beginPath();a.forEach((x,i)=>{let px=10+i*(r.width-20)/(a.length-1),py=10+(mx-x.total)*(r.height-20)/(mx-mn);i?g.lineTo(px,py):g.moveTo(px,py)});g.stroke()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));document.querySelector("#"+b.dataset.tab).classList.remove("hidden");if(b.dataset.tab==="data")drawChart()});
document.querySelector("#snapshot").onclick=()=>{state.history.push({at:new Date().toISOString(),total:total(),cards:Object.fromEntries(state.cards.map(x=>[x.id,x.value]))});save();render()};
document.querySelector("#addWatch").onclick=()=>{let name=prompt("Carta a seguir");if(!name)return;let target=prompt("Precio objetivo en €","30");state.watch.push({name,target:+target||0});save();render()};window.removeWatch=i=>{state.watch.splice(i,1);save();render()};
const dlg=document.querySelector("#cardDialog"),form=document.querySelector("#cardForm");document.querySelector("#addCard").onclick=()=>dlg.showModal();document.querySelector("#saveCard").onclick=async e=>{e.preventDefault();if(!form.reportValidity())return;let f=new FormData(form),file=f.get("photo"),photo=null;if(file&&file.size)photo=await resize(file);state.cards.push({id:crypto.randomUUID(),name:f.get("name"),set:f.get("set"),grade:+f.get("grade"),value:+f.get("value")||0,cert:f.get("cert"),purchase:f.get("purchase")===""?null:+f.get("purchase"),photo,icon:"🃏"});save();render();form.reset();dlg.close()};
function resize(file){return new Promise(ok=>{let im=new Image(),rd=new FileReader();rd.onload=()=>im.src=rd.result;im.onload=()=>{let max=900,s=Math.min(1,max/im.width),cv=document.createElement("canvas");cv.width=im.width*s;cv.height=im.height*s;cv.getContext("2d").drawImage(im,0,0,cv.width,cv.height);ok(cv.toDataURL("image/jpeg",.78))};rd.readAsDataURL(file)})}
document.querySelector("#export").onclick=()=>{let blob=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="card-vault-backup-"+new Date().toISOString().slice(0,10)+".json";a.click();URL.revokeObjectURL(a.href)};
document.querySelector("#import").onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.cards)throw 0;state=x;save();render();alert("Backup restaurado")}catch{alert("Backup no válido")}};
render();